
print("Identitas Pribadi")
print("==================")

nama = str("Muhammad Safely Afnan")
Nim = str("I0320070")
Kls = str("B")
prodi = str("Teknik Industri")
univ = str("Universitas Sebelas Maret")
TL = str("Temanggung")
tgll = str("23 November 2001")
almt = str("Rejosari RT 7/RW 2, Kowangan, Temanggung.")
kost = str("Pucangsawit RT 2/RW 2, Jebres, Surakarta")
gndr = str("Laki-laki")
tinggi = int("175")
berat = float("55.5")
umur = int("19")
sepatu = float("41")

print ("Biodata")
print ("1. Nama :", nama)
print ("2. NIM:", Nim)
print ("3. Kelas :", Kls)
print ("4. Program Studi :", prodi)
print ("5. Universitas :", univ)
print ("6. Tempat Lahir :", TL)
print ("7. Tanggal Lahir :", tgll)
print ("7. Alamat :", almt)
print ("7. Alamat Kost :", kost)
print ("8. Jenis Kelamain :", gndr)
print ("9. Tinggi :", tinggi)
print ("10. Berat :", berat)
print ("11. Umur :", umur)
print ("11. Ukuran Sepatu :", sepatu)


print ("===============================================================")
print ("===============================================================")
print ("===============================================================")
